### ISSUE TITLE
[Feature Request] Do not save chat history

### ISSUE THREAD

**Issue by bq866js3js9dwvs9** [evilcorpltd/aTox#1048] opened 2022-06-07 15:18 UTC
I think you should consider adding one of qTox's features to aTox, namely not logging the chat history. This feature could help protecting conversations against someone who may gain physical access to the device in future. I know that for now one can only delete the conversation manually, but the issue is that the conversation was previously saved on device so it's not really permanently deleted. If the conversation wouldn't be saved on the device in the first place, it would be much more difficult to recover it forensically.

You could either implement it globally or on per-contact basis and messages would be stored until the application is fully closed i.e. not working in background nor foreground anymore.

**Comment by theAkito** [comment] 2022-10-29 13:12
Even then, it would be still theoretically possible to recover the messages.

**Comment by robinlinden** [comment] 2022-10-29 13:41
This is a nice idea still, and it's planned to be added. Closing this as a duplicate of #906.

**Closed by robinlinden** 2022-10-29 13:41 UTC
