### ISSUE TITLE
Crash adding contact

### ISSUE THREAD

**Issue by jpage4500** [evilcorpltd/aTox#1248] opened 2024-07-30 17:29 UTC
Hi, I noticed the app crashes right after clicking on the ADD button in add contact screen. I can see from the log that this was a contact which I already tried adding previously and that's true so I guess it's not something that will happen often. But, as a developer I figured you'd want to know to maybe show an error message or maybe just take the user to the already invited contact/conversation screen

```
 FATAL EXCEPTION: DefaultDispatcher-worker-5
 Process: ltd.evilcorp.atox, PID: 18402
 im.tox.tox4j.core.exceptions.ToxFriendAddException: Error code: ALREADY_SENT
 	at im.tox.tox4j.impl.jni.ToxCoreJni.toxFriendAdd(Native Method)
 	at m5.j.y(:11)
 	at y3.a.s(:2)
 	at l4.j0.run(Unknown Source:86)
 	at r4.a.o(Unknown Source:0)
 	at r4.a$a.run(:5)
```

**Comment by robinlinden** [comment] 2024-08-11 21:16
Duplicate of #348, fixed in #402. I'll finish up the release stuff and get a version out with it soon.

That said, I appreciate the reports of rare bugs as well. :P It shouldn't be possible to crash aTox like that and it was an oversight.

**Closed by robinlinden** 2024-08-11 21:16 UTC
