### ISSUE TITLE
Friends list doesn't seem sorted

### ISSUE THREAD

**Issue by anthonybilinski** [evilcorpltd/aTox#276] opened 2019-11-11 19:49 UTC
Android 10, master nightly from ~2019-11-06.

My friends list looks like:
```
A: never (but aTox has sent a message)
B: Nov 9
Unknown: Never
Unknown: Never
.
.
.
C: never
D: Nov 11
E: Nov 7
F: Nov 8
```
I don't see any obvious last activity sorting, last message received sorting, or alphabetical sorting. I think just last message sent/received would be better than just last received, but either would be good.

Note that this profile was imported from Antox, which could be related.

**Comment by robinlinden** [comment] 2019-11-11 19:51
Yeah, this was caused by not using a sensible time format in the database and was fixed in 36feb18b8a132996981a33fe4da02093e8c65a09, but thanks for the report!

**Closed by robinlinden** 2019-11-11 19:51 UTC
