### ISSUE TITLE
F-Droid Build is Outdated 

### ISSUE THREAD

**Issue by giiutfff** [evilcorpltd/aTox#1221] opened 2024-03-27 16:41 UTC
The latest build on F-Droid is more than two years old. Could you please kindly update it. Thanks a lot.

**Comment by robinlinden** [comment] 2024-03-28 00:23
The F-Droid maintainers ran into issues building the last release, but there's a new aTox release in the works and that should trigger a new F-Droid release as well.

We're finishing up a c-toxcore 0.2.19 release right now, but once that's done I'll finish up the last bits needed for a new release here as well.

See: #933

**Comment by robinlinden** [comment] 2024-11-10 22:52
@licaon-kter 0.8.0 has been released now. :) Please let me know if you run into any issues with building aTox on F-Droid.

**Comment by licaon-kter** [comment] 2024-11-11 15:30
wip https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16555

> I forgot, where to check their automatic build pipelines

https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Comment by robinlinden** [comment] 2024-11-14 01:41
That's amazing, licaon-kter, thank you so much. :D If there's anything we can do to make building aTox easier, feedback is happily accepted. :)

**Comment by licaon-kter** [comment] 2024-11-14 10:01
@robinlinden yes and no, maybe you can look at the diff log and we can come as close as possible to yours?

switching to a reproducible build is hard(er) since user can't (yet) be switched in a friendly way, they'd need to backup, uninstall then reinstall and restore.

but would be nice to be reproducible in general, ref: https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds

**Comment by robinlinden** [comment] 2024-11-17 19:01
Thank you! Will have a look at making the build more reproducible. One of the longer-term goals is to support building w/ Bazel which is more designed for that kind of thing. Will see what we can do to make the current build system more reproducible as well, though. :)

Closing this as resolved, now that we have v0.8.0 in FDroid.

**Closed by robinlinden** 2024-11-17 19:01 UTC
Labels: question
