### ISSUE TITLE
Make Settings Change color Theme and size fonts

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#640] opened 2021-03-15 13:09 UTC
Such a topic was already, but I will try to duplicate it
It would be nice to be able to choose the color  yourself or add your own # Hex code
and not just default colors

It would also be nice to be able to change the color and size of the text

## Example Screenshot
![Theme_color](https://user-images.githubusercontent.com/43858033/111157748-ec8eae00-859f-11eb-9d3d-3af75677c898.png)

**Comment by robinlinden** [comment] 2021-03-15 14:55
Duplicate of #620

**Closed by robinlinden** 2021-03-15 14:55 UTC
