### ISSUE TITLE
Manager Output File List

### ISSUE THREAD

**Issue by xbvrhlmb** [evilcorpltd/aTox#748] opened 2021-05-27 21:30 UTC
## Desc
If the files that are received are not deleted, then it would be great to have an additional panel where you can see all these files and manually delete them (without flipping to the top of a long conversation)
so the user will intuitively understand where the files

# Step
join to dialog
swipe right (All Media Files) and add to top menu "All Media Files"
and show list all files in this dialog

## Example Screenshot in Session Desktop
![1](https://user-images.githubusercontent.com/43858033/119899523-dca22b80-bf4b-11eb-9157-d6ee44d36110.png)

**Comment by robinlinden** [comment] 2021-05-27 21:59
Duplicate of #654

**Closed by robinlinden** 2021-05-27 21:59 UTC
Labels: duplicate
