### ISSUE TITLE
Feature request: add voice chat

### ISSUE THREAD

**Issue by Klagio** [evilcorpltd/aTox#357] opened 2020-02-10 15:33 UTC
Missing an Android tox app that works well with only voice calls

**Comment by robinlinden** [comment] 2020-02-10 16:44
Closing this as it's a duplicate of #158. If you want to "vote" on a feature you can use the emoji functionality in GitHub or comment on it. :P Having multiple of the same issue will make keeping information up-to-date difficult.

**Closed by robinlinden** 2020-02-10 16:44 UTC
